### ISSUE TITLE
Compilation failure on OSX with M1 CPU

### ISSUE THREAD

**Issue by nmathewson** [Nugine/rlimit#35]
Hello! Since upgrading to 0.8, I've had a compilation failure when building on my m1 laptop:

```
   Compiling rlimit v0.8.0 (/Users/nickm/src/crates/rlimit)
error[E0425]: cannot find value `RLIM_INFINITY` in module `C`
 --> src/unix.rs:7:30
  |
7 | pub const INFINITY: u64 = C::RLIM_INFINITY as u64;
  |                              ^^^^^^^^^^^^^ not found in `C`
error[E0422]: cannot find struct, variant or union type `rlimit` in module `C`
  --> src/unix.rs:23:19
   |
23 |     let rlim = C::rlimit {
   |                   ^^^^^^ not found in `C`
   |
help: consider importing this struct
   |
1  | use libc::rlimit;

... [many similar issues follow] ...

Some errors have detailed explanations: E0422, E0425.
For more information about an error, try `rustc --explain E0422`.
error: could not compile `rlimit` due to 29 previous errors
```

This problem seems to occur because there is no entry for `target_arch="aarch64", target_os="macos"` in bindings.rs.

I tried to rectify this by running "scripts/codegen.sh", but got a compilation failure from the C++ code:

```
./scripts/codegen.cpp:223:52: error: unknown type name 'rlim64_t'; did you mean 'rlim_t'?
    cout << "pub type rlim_t = " << rust_type_name<rlim64_t>() << ";" << endl;
                                                   ^~~~~~~~
                                                   rlim_t
```

As near as I can tell, my SDK does not have a separate rlim64_t or getrlimit64, so I tried running again with CODEGEN64 disabled.
 
I'll try writing a PR with the results.

**Comment by Nugine** [comment]
Resolved by #36.
The fix has been published by [v0.8.1](https://github.com/Nugine/rlimit/blob/master/CHANGELOG.md#081---2022-04-01).

**Comment by nmathewson** [comment]
Thanks for the fast response!
